
== Quartz Enterprise Job Scheduler
:stylesheet: dark.css

 What is the Quartz Job Scheduling Library?

Quartz is a richly featured, open source job scheduling library that can be integrated within virtually any Java application - from the smallest stand-alone application to
the largest e-commerce system. Quartz can be used to create
simple or complex schedules for executing tens, hundreds, or even
tens-of-thousands of jobs; jobs whose tasks are defined as standard Java
components that may execute virtually anything you may program them to do.
The Quartz Scheduler includes many enterprise-class features, such as
support for JTA transactions and clustering.

// What Can Quartz Do For You?
//
//If your application has tasks that need to occur at given moments in time, or if your system has recurring maintenance jobs then Quartz may be your ideal solution.
//
//Sample uses of job scheduling with Quartz:
//
//* Driving Process Workflow: As a new order is initially placed, schedule a Job to fire in exactly 2 hours, that will check the status of that order, and trigger a warning notification if an order confirmation message has not yet been received for the order, as well as changing the order’s status to 'awaiting intervention'.
//
//* System Maintenance: Schedule a job to dump the contents of a database into an XML file every business day (all weekdays except holidays) at 11:30 PM.
//
//* Providing reminder services within an application.

=== Features
*Runtime Environments*

* Quartz can run embedded within another free standing application

* Quartz can be instantiated within an application server (or servlet container), and participate in XA transactions

* Quartz can run as a stand-alone program (within its own Java Virtual Machine), to be used via RMI

* Quartz can be instantiated as a cluster of stand-alone programs (with load-balance and fail-over capabilities) for the execution of jobs

=== Create Quartz Job.
* *@param* jobClass  Class whose executeInternal() method needs to be called.
* *@param* isDurable Job needs to be persisted even after completion. if true, job will be persisted, not otherwise.
* *@param* jobName   Job name.
* *@param* jobGroup  Job group.
* *@return* JobDetail object

    public JobDetail createJob(Class<? extends QuartzJobBean> jobClass, boolean isDurable, String jobName, String jobGroup) {
        JobDetailFactoryBean factoryBean = new JobDetailFactoryBean();
        factoryBean.setJobClass(jobClass);
        factoryBean.setDurability(isDurable);
        factoryBean.setName(jobName);
        factoryBean.setGroup(jobGroup);
        JobDataMap jobDataMap = new JobDataMap();
        jobDataMap.put(jobName + jobGroup, jobClass.getName());
        factoryBean.setJobDataMap(jobDataMap);
        factoryBean.afterPropertiesSet();
        return factoryBean.getObject();
    }

=== Create cron trigger

 * *@param* triggerName        Trigger name.
 * *@param* startTime          Trigger start time.
 * *@param* cronExpression     Cron expression.
 * *@param* misFireInstruction Misfire instruction (what to do in case of misfire happens).
 * *@return* {@link CronTrigger}

    public CronTrigger createCronTrigger(String triggerName, Date startTime, String cronExpression, int misFireInstruction) {
        CronTriggerFactoryBean factoryBean = new CronTriggerFactoryBean();
        factoryBean.setName(triggerName);
        factoryBean.setStartTime(startTime);
        factoryBean.setCronExpression(cronExpression);
        factoryBean.setMisfireInstruction(misFireInstruction);
        try {
            factoryBean.afterPropertiesSet();
        } catch (ParseException e) {
            log.error(e.getMessage(), e);
        }
        return factoryBean.getObject();
    }

=== Create simple trigger.

 * *@param* triggerName        Trigger name.
 * *@param* startTime          Trigger start time.
 * *@param* repeatTime         Job repeat period mills
 * *@param* misFireInstruction Misfire instruction (what to do in case of misfire happens).
 * *@return* {@link SimpleTrigger}

   public SimpleTrigger createSimpleTrigger(String triggerName, Date startTime, Long repeatTime, int misFireInstruction) {
        SimpleTriggerFactoryBean factoryBean = new SimpleTriggerFactoryBean();
        factoryBean.setName(triggerName);
        factoryBean.setStartTime(startTime);
        factoryBean.setRepeatInterval(repeatTime);
        factoryBean.setRepeatCount(SimpleTrigger.REPEAT_INDEFINITELY);
        factoryBean.setMisfireInstruction(misFireInstruction);
        factoryBean.afterPropertiesSet();
        return factoryBean.getObject();
    }

=== Available Method to call

     * It start All the job schedulers that in the database.

    void startAllSchedulers();


     * It Create New Job And Switch JobStore to persistence table

     * *@param* jobInfo JobInformation(Ex: timingInfo, JobName etc)

    void scheduleNewJob(SchedulerJobInfo jobInfo);


     * It Update the job information and reschedule the information into JobStore

     * *@param* jobInfo JobInformation(Ex: timingInfo, JobName, jobGroup etc)

    void updateScheduleJob(SchedulerJobInfo jobInfo);


     * It takes JobName and removes the job from the JobStore

     * *@param* jobName Name of the running job
     * *@return* {@link boolean}

    boolean unScheduleJob(String jobName);


     * loops through all the triggers having a reference to this job, to un-schedule them

     * *@param* jobInfo JobInformation(Ex: timingInfo, JobName, jobGroup etc)
     * *@return* {@link boolean}

    boolean deleteJob(SchedulerJobInfo jobInfo);


     * It pause the currently running job.

     * *@param* jobInfo JobInformation(Ex: timingInfo, JobName, jobGroup etc)
     * *@return* {@link boolean}

    boolean pauseJob(SchedulerJobInfo jobInfo);


     * It resume the pausing jobs and job start running again

     * *@param* jobInfo JobInformation(Ex: timingInfo, JobName, jobGroup etc)
     * *@return* {@link boolean}

    boolean resumeJob(SchedulerJobInfo jobInfo);


     * if there is needed any Immediate call/hit of a particular job then method can be called

     * *@param* jobInfo JobInformation(Ex: timingInfo, JobName, jobGroup etc)
     * *@return* {@link boolean}

    boolean startJobNow(SchedulerJobInfo jobInfo);


     * Shutdown JobStore

    void shutdownScheduler();

